version: '3.8'
services: 
  sampleproject:
      image: react
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        NODE_ENV: production
      ports:
        - 3000:3000